# Generated by Django 5.2.17 on 2026-09-30 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_order_book_remove_order_quantity_order_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                        ],
                        max_length=8,
                        verbose_name="Language",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("author", models.CharField(max_length=255, verbose_name="Author")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="main.book",
                        verbose_name="Book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book translation",
                "verbose_name_plural": "Book translations",
                "ordering": ["language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "language"), name="unique_book_language"
                    )
                ],
            },
        ),
    ]
