# Generated by Django 5.2.17 on 2026-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Job",
                    ),
                ),
                (
                    "last_started",
                    models.DateTimeField(null=True, verbose_name="Last started"),
                ),
                (
                    "last_finished",
                    models.DateTimeField(null=True, verbose_name="Last finished"),
                ),
                (
                    "succeeded",
                    models.BooleanField(default=False, verbose_name="Succeeded"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
            ],
            options={
                "verbose_name": "Scheduled job",
                "verbose_name_plural": "Scheduled jobs",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="booktranslation",
            name="machine_translated",
            field=models.BooleanField(default=False, verbose_name="Machine translated"),
        ),
        migrations.AddField(
            model_name="booktranslation",
            name="reviewed",
            field=models.BooleanField(default=True, verbose_name="Reviewed"),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
