# Generated by Django 5.2.17 on 2026-09-30 19:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_rates(apps, schema_editor):
    """Move ExchangeRate rows into Currency and add the base currency."""
    Currency = apps.get_model("main", "Currency")
    ExchangeRate = apps.get_model("main", "ExchangeRate")
    Currency.objects.get_or_create(code="USD", defaults={"rate": 1})
    # The starting set. Rates come from the feed on the next update.
    for code in ("EUR", "RUB"):
        Currency.objects.get_or_create(code=code)
    for old in ExchangeRate.objects.all():
        Currency.objects.update_or_create(code=old.currency, defaults={"rate": old.rate})


def restore_rates(apps, schema_editor):
    Currency = apps.get_model("main", "Currency")
    ExchangeRate = apps.get_model("main", "ExchangeRate")
    for currency in Currency.objects.exclude(code="USD").exclude(rate=None):
        ExchangeRate.objects.update_or_create(
            currency=currency.code, defaults={"rate": currency.rate}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_refunds_scheduler_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three letter ISO 4217 code."
                            )
                        ],
                        verbose_name="Code",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Leave empty to fetch it from the rate feed.",
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                        verbose_name="Units per 1 USD",
                    ),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="0 for currencies without minor units, such as JPY.",
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Decimal places",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "manual_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Keep the rate as entered instead of updating it from the feed.",
                        verbose_name="Manual rate",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(copy_rates, restore_rates),
        migrations.DeleteModel(
            name="ExchangeRate",
        ),
    ]
