# Generated by Django 5.2.17 on 2026-09-30 19:44

import django.core.validators
import django.db.models.deletion
import main.models
from decimal import Decimal
from django.db import migrations, models


EU = [
    "AT",
    "BE",
    "BG",
    "CY",
    "CZ",
    "DE",
    "DK",
    "EE",
    "ES",
    "FI",
    "FR",
    "GR",
    "HR",
    "HU",
    "IE",
    "IT",
    "LT",
    "LU",
    "LV",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "SE",
    "SI",
    "SK",
]

ZONES = [
    (
        "United States",
        ["US"],
        [
            (
                "standard",
                {"en": "Standard", "ru": "Стандартная", "fr": "Standard", "de": "Standard"},
                "4.99",
                "35.00",
                3,
                6,
            ),
            (
                "express",
                {"en": "Express", "ru": "Экспресс", "fr": "Express", "de": "Express"},
                "14.99",
                None,
                1,
                2,
            ),
        ],
    ),
    (
        "European Union",
        EU,
        [
            (
                "standard",
                {"en": "Standard", "ru": "Стандартная", "fr": "Standard", "de": "Standard"},
                "6.99",
                "50.00",
                4,
                8,
            ),
            (
                "express",
                {"en": "Express", "ru": "Экспресс", "fr": "Express", "de": "Express"},
                "19.99",
                None,
                2,
                3,
            ),
        ],
    ),
    (
        "Russia",
        ["RU"],
        [
            (
                "standard",
                {
                    "en": "Russian Post",
                    "ru": "Почта России",
                    "fr": "Poste russe",
                    "de": "Russische Post",
                },
                "5.99",
                "40.00",
                5,
                14,
            ),
            (
                "courier",
                {"en": "Courier", "ru": "Курьер", "fr": "Coursier", "de": "Kurier"},
                "11.99",
                None,
                2,
                4,
            ),
        ],
    ),
    (
        "Rest of the world",
        [],
        [
            (
                "international",
                {
                    "en": "International",
                    "ru": "Международная",
                    "fr": "International",
                    "de": "International",
                },
                "12.99",
                "80.00",
                7,
                21,
            ),
        ],
    ),
]

# Reduced VAT rates for printed books. US sales tax depends on the state and
# is not collected here.
TAX_RATES = {
    "AT": "10.00",
    "BE": "6.00",
    "DE": "7.00",
    "ES": "4.00",
    "FR": "5.50",
    "IT": "4.00",
    "NL": "9.00",
    "PL": "5.00",
    "PT": "6.00",
    "RU": "10.00",
}


def fill_defaults(apps, schema_editor):
    Order = apps.get_model("main", "Order")
    Order.objects.update(subtotal=models.F("total"))

    ShippingZone = apps.get_model("main", "ShippingZone")
    ShippingMethod = apps.get_model("main", "ShippingMethod")
    TaxRate = apps.get_model("main", "TaxRate")
    if not ShippingZone.objects.exists():
        for name, countries, methods in ZONES:
            zone = ShippingZone.objects.create(name=name, countries=countries)
            for position, (code, names, price, free_from, min_days, max_days) in enumerate(methods):
                ShippingMethod.objects.create(
                    zone=zone,
                    code=code,
                    names=names,
                    price=price,
                    free_from=free_from,
                    min_days=min_days,
                    max_days=max_days,
                    position=position,
                )
    for country, rate in TAX_RATES.items():
        TaxRate.objects.get_or_create(country=country, defaults={"rate": rate})


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_currency_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='ISO codes, e.g. ["DE", "FR"]. Empty means the rest of the world.',
                        validators=[main.models.validate_country_list],
                        verbose_name="Countries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping zone",
                "verbose_name_plural": "Shipping zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "country",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        validators=[main.models.validate_country],
                        verbose_name="Country",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rate, %",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="VAT", max_length=40, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Tax rate",
                "verbose_name_plural": "Tax rates",
                "ordering": ["country"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="address_line1",
            field=models.CharField(blank=True, max_length=200, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="order",
            name="address_line2",
            field=models.CharField(blank=True, max_length=200, verbose_name="Address, line 2"),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=2, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_max_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_min_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Full name"),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Postal code"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Shipping",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(blank=True, max_length=100, verbose_name="Shipping method"),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Tax",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Tax rate, %",
            ),
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, verbose_name="Code")),
                ("names", models.JSONField(default=dict, verbose_name="Names")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Price (USD)"),
                ),
                (
                    "free_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Orders at or above this subtotal ship free.",
                        max_digits=8,
                        null=True,
                        verbose_name="Free from (USD)",
                    ),
                ),
                (
                    "min_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Delivery from (days)"
                    ),
                ),
                (
                    "max_days",
                    models.PositiveSmallIntegerField(default=7, verbose_name="Delivery to (days)"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="main.shippingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping method",
                "verbose_name_plural": "Shipping methods",
                "ordering": ["zone", "position", "price"],
                "constraints": [
                    models.UniqueConstraint(fields=("zone", "code"), name="unique_zone_method")
                ],
            },
        ),
        migrations.RunPython(fill_defaults, migrations.RunPython.noop),
    ]
