# Generated by Django 5.2.17 on 2026-09-30 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def move_refunds(apps, schema_editor):
    """Turn the old one-refund-per-payment fields into Refund rows."""
    Payment = apps.get_model("main", "Payment")
    Refund = apps.get_model("main", "Refund")
    for payment in Payment.objects.filter(status="refunded"):
        Refund.objects.create(
            payment=payment,
            amount=payment.amount,
            status="succeeded",
            provider_refund_id=payment.refund_id,
        )
    for payment in Payment.objects.filter(status="succeeded", needs_refund=True):
        Refund.objects.create(payment=payment, amount=payment.amount, status="pending")


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_shipping_and_taxes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("partially_refunded", "Partially refunded"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="Reason"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(blank=True, max_length=255, verbose_name="Provider id"),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Attempts"),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=255, verbose_name="Last error"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="main.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(move_refunds, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="payment",
            name="refund_id",
        ),
    ]
